// Syllabus data model for scalable lessons and procedures
export const stages = [
  {
    id: 1,
    name: 'Very Early (First ~5–10 Hours)',
    locked: false,
    lessons: [
      'Taxiing Using Rudder Pedals',
      'Normal Takeoff Procedure',
      'Rotation & Initial Climb',
      'Straight & Level Flight (Altitude, Heading Hold)',
      'Vy/Vx Climb Performance',
      'Taxi Clearance Request',
      'Turns to Headings (Standard Rate)',
      'Climbing & Descending Turns',
      'Traffic Pattern Entry & Position Reports',
      'Normal Landing Procedure',
      'Full Stop Landings',
      'Go-Around/Missed Approach Procedures',
      'Touch-and-Go Landings',
      'Use of Flaps for Landing',
    ],
  },
  {
    id: 2,
    name: 'Early Training (Pre-Solo Skill Building)',
    locked: true,
    lessons: [
      'Crosswind Takeoff Technique',
      'Crosswind Landing Technique',
      'Slow Flight (Configuration, Control)',
      'Power-Off Stalls (Approach to Landing Stall)',
      'Power-On Stalls (Takeoff/Departure Stall)',
      'Rectangular Course',
      'Turns Around a Point',
      'S-Turns Across a Road',
      'Basic Instrument Maneuvers (Straight & Level, Turns, Climbs, Descents)',
      'Use of Backup Instruments',
      'Engine Failure During Takeoff Roll',
      'Engine Failure After Takeoff',
      'Engine Failure in Flight (ABC: Airspeed, Best Field, Checklist)',
      'Forced Landing (Field Selection, Approach, Landing)',
    ],
  },
  {
    id: 3,
    name: 'Solo Readiness / Early Solo Phase',
    locked: true,
    lessons: [
      'Solo Takeoffs & Landings',
      'Solo Traffic Pattern Operations',
      'Short Field Takeoff Technique',
      'Short Field Landing Technique',
      'Soft Field Takeoff Technique',
      'Soft Field Landing Technique',
      'Forward Slip to Landing',
      'Emergency Descent',
      'Recovery from Unusual Attitudes',
      'Electrical Failure (Alternator/Generator Out)',
      'Fire (Engine, Cabin, Electrical)',
    ],
  },
  {
    id: 4,
    name: 'Cross Country Phase',
    locked: true,
    lessons: [
      'Sectional Chart Reading',
      'Use of Electronic Flight Bag (ForeFlight, Garmin Pilot)',
      'Pilotage (Visual Reference Points)',
      'Dead Reckoning Navigation',
      'GPS Navigation (Direct-To, Flight Plan, Waypoints)',
      'VOR Navigation (Tune, Identify, Track Radials)',
      'Radio Navigation (VOR, ILS, GPS, DME, ADF)',
      'Diversion to Alternate Airport',
      'Cross Country Flight Execution',
      'Solo Cross Country Planning & Execution',
    ],
  },
  {
    id: 5,
    name: 'Advanced / Night / Checkride Prep',
    locked: true,
    lessons: [
      'Night Taxi Procedures',
      'Night Takeoff & Landing',
      'Night Traffic Pattern Operations',
      'Night Navigation (Visual, Electronic)',
      'Solo Night Flight',
      'Solo Emergency Procedures',
    ],
  },
];

// Procedures tab will be populated with all other tasks as yes/no items
